### ISSUE TITLE
Issues Service

### ISSUE THREAD

**Issue by andrew** [ecosyste-ms/roadmap#6]
Collect and generate statistics for issues and pull requests 

Interesting stats include:
- average time to close issues
- average time to close pull requests
- number of unique issue creators
- number of unique pull request creators
- average number of comments on an issue
- average number of comments on an pull request
- label breakdowns
- stats over certain date ranges
- bot activity

**Comment by Ly0n** [comment]
I find it helpful to see if projects create commits in conjunction with closing issues. This shows that the project has a development process that enables multiple developers.

**Comment by andrew** [comment]
There's a handy table of events we can get for github issues and pull requests in the two apis they have access to here: https://gist.github.com/dahlbyk/229f6ee762e2b0b45f3add7c2459e64a

**Comment by andrew** [comment]
Work is happening over here: https://github.com/ecosyste-ms/issues

**Comment by andrew** [comment]
@Ly0n here's how it's looking so far, will be deploying it soon:

<img width="1456" alt="Screenshot 2023-05-03 at 16 42 22" src="https://user-images.githubusercontent.com/1060/235967669-47813e7e-fd6e-4170-8536-d0acee9f27e1.png">

**Comment by andrew** [comment]
The service is now online, still a little bit of setup to do but mostly ready: https://issues.ecosyste.ms/hosts/GitHub/repositories/octobox%2Foctobox

**Comment by Ly0n** [comment]
The "Issue Author Associations" are perfect for our study. 
@joshhopkins

**Comment by joshhopkins** [comment]
Indeed @Ly0n . Great stuff @andrew.
